# Generated by Django 5.2.5 on 2025-09-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='adress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
