# Generated by Django 5.2.5 on 2025-09-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='lastnime',
            new_name='lastname',
        ),
    ]
