# Generated by Django 5.2.5 on 2025-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_lastnime_members_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='joined_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
