# Generated by Django 5.2.6 on 2025-09-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membershipapplication_remove_userprofile_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipApplication',
        ),
    ]
