# Generated by Django 5.2.6 on 2025-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_role_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('librarian', 'librarian')], default='user', max_length=20),
        ),
    ]
